In [1]:
import pandas as pd
import numpy as np
import os
from joblib import dump, load
from sklearn.pipeline import Pipeline
from sklearn import set_config
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from dotenv import load_dotenv

In [2]:
import joblib

In [3]:
joblib.__version__

'1.0.1'

In [4]:
import sklearn

In [5]:
sklearn.__version__

'1.0.2'

In [6]:
load_dotenv()
data_basepath = os.environ['DATA_BASEPATH']
fn = 'Bonität Auszug 14-10-2022 export.csv'

In [7]:
df = pd.read_csv(os.path.join(data_basepath, fn), sep=';')

In [8]:
y = df['Risiko']

In [9]:
df['Geschlecht']=df['Geschlecht'].replace({0:'weiblich', 1:'männlich'})

In [10]:
df_X = df.drop(['Index', 'Risiko'], axis=1)

In [11]:
df_X

Alter Geschlecht                       Arbeitsstelle Wohnsituation  \
0       67   weiblich              mittlere Qualifikation      Eigentum   
1       22   männlich              mittlere Qualifikation      Eigentum   
2       49   weiblich  niedrige Qualifikation - permanent      Eigentum   
3       45   weiblich              mittlere Qualifikation     kostenlos   
4       53   weiblich              mittlere Qualifikation     kostenlos   
..     ...        ...                                 ...           ...   
992     31   männlich  niedrige Qualifikation - permanent      Eigentum   
993     40   weiblich                  hohe Qualifikation      Eigentum   
994     38   weiblich              mittlere Qualifikation      Eigentum   
995     23   weiblich              mittlere Qualifikation     kostenlos   
996     27   weiblich              mittlere Qualifikation      Eigentum   

    Sparkonto Lohnkonto  Kreditbetrag  Laufzeit         Verwendungszweck  
0         NaN    gering          5076         6  Unterhaltungselektronik  
1      gering    mittel         25840        48  Unterhaltungselektronik  
2      gering       NaN          9101        12               Ausbildung  
3      gering    gering         34224        42     Wohnungsreinrichtung  
4      gering    gering         21146        24                 Fahrzeug  
..        ...       ...           ...       ...                      ...  
992    gering       NaN          7538        12     Wohnungsreinrichtung  
993    gering    gering         16748        30                 Fahrzeug  
994    gering       NaN          3491        12  Unterhaltungselektronik  
995    gering    gering          8011        45  Unterhaltungselektronik  
996    mittel    mittel         19869        45                 Fahrzeug  

[997 rows x 9 columns]

In [12]:
cat_features = ['Geschlecht','Arbeitsstelle','Wohnsituation','Sparkonto','Lohnkonto','Verwendungszweck']
num_features = ['Alter', 'Kreditbetrag', 'Laufzeit']

In [13]:
df_X[cat_features]

Geschlecht                       Arbeitsstelle Wohnsituation Sparkonto  \
0     weiblich              mittlere Qualifikation      Eigentum       NaN   
1     männlich              mittlere Qualifikation      Eigentum    gering   
2     weiblich  niedrige Qualifikation - permanent      Eigentum    gering   
3     weiblich              mittlere Qualifikation     kostenlos    gering   
4     weiblich              mittlere Qualifikation     kostenlos    gering   
..         ...                                 ...           ...       ...   
992   männlich  niedrige Qualifikation - permanent      Eigentum    gering   
993   weiblich                  hohe Qualifikation      Eigentum    gering   
994   weiblich              mittlere Qualifikation      Eigentum    gering   
995   weiblich              mittlere Qualifikation     kostenlos    gering   
996   weiblich              mittlere Qualifikation      Eigentum    mittel   

    Lohnkonto         Verwendungszweck  
0      gering  Unterhaltungselektronik  
1      mittel  Unterhaltungselektronik  
2         NaN               Ausbildung  
3      gering     Wohnungsreinrichtung  
4      gering                 Fahrzeug  
..        ...                      ...  
992       NaN     Wohnungsreinrichtung  
993    gering                 Fahrzeug  
994       NaN  Unterhaltungselektronik  
995    gering  Unterhaltungselektronik  
996    mittel                 Fahrzeug  

[997 rows x 6 columns]

In [14]:
set_config(display="diagram")

In [15]:
cat_transformer = Pipeline(
    steps=[
        ('onehot', OneHotEncoder(handle_unknown='ignore',dtype='int')),
        ('imputer', SimpleImputer(strategy="constant", fill_value=-1))]
)

In [16]:
preprocessor = ColumnTransformer(transformers=[('cat', cat_transformer, cat_features)], remainder='passthrough', verbose_feature_names_out=False)

In [17]:
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 Pipeline(steps=[('onehot',
                                                  OneHotEncoder(dtype='int',
                                                                handle_unknown='ignore')),
                                                 ('imputer',
                                                  SimpleImputer(fill_value=-1,
                                                                strategy='constant'))]),
                                 ['Geschlecht', 'Arbeitsstelle',
                                  'Wohnsituation', 'Sparkonto', 'Lohnkonto',
                                  'Verwendungszweck'])],
                  verbose_feature_names_out=False)

In [18]:
clf = Pipeline(
    steps=[("preprocessor", preprocessor),
           ("classifier", LogisticRegression(max_iter=10000))
          ]
)

In [19]:
clf

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(dtype='int',
                                                                                 handle_unknown='ignore')),
                                                                  ('imputer',
                                                                   SimpleImputer(fill_value=-1,
                                                                                 strategy='constant'))]),
                                                  ['Geschlecht',
                                                   'Arbeitsstelle',
                                                   'Wohnsituation', 'Sparkonto',
                                                   'Lohnkonto',
                                                   'Verwendungszweck'])],
                                   verbose_feature_names_out=False)),
                ('classifier', LogisticRegression(max_iter=10000))])

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df_X, y, test_size=0.2, random_state=42)

In [21]:
clf.fit(X_train, y_train)
print("model score: %.3f" % clf.score(X_test, y_test))

model score: 0.730


In [22]:
clf.named_steps['preprocessor'].transform(df_X)

array([[    0,     1,     0, ...,    67,  5076,     6],
       [    1,     0,     0, ...,    22, 25840,    48],
       [    0,     1,     0, ...,    49,  9101,    12],
       ...,
       [    0,     1,     0, ...,    38,  3491,    12],
       [    0,     1,     0, ...,    23,  8011,    45],
       [    0,     1,     0, ...,    27, 19869,    45]], dtype=int64)

In [24]:
clf.named_steps['preprocessor']

ColumnTransformer(remainder='passthrough',
                  transformers=[('cat',
                                 Pipeline(steps=[('onehot',
                                                  OneHotEncoder(dtype='int',
                                                                handle_unknown='ignore')),
                                                 ('imputer',
                                                  SimpleImputer(fill_value=-1,
                                                                strategy='constant'))]),
                                 ['Geschlecht', 'Arbeitsstelle',
                                  'Wohnsituation', 'Sparkonto', 'Lohnkonto',
                                  'Verwendungszweck'])],
                  verbose_feature_names_out=False)

In [25]:
df_X.columns

Index(['Alter', 'Geschlecht', 'Arbeitsstelle', 'Wohnsituation', 'Sparkonto',
       'Lohnkonto', 'Kreditbetrag', 'Laufzeit', 'Verwendungszweck'],
      dtype='object')

In [26]:
data=[{'Alter': 67, 'Geschlecht': 'weiblich', 'Arbeitsstelle': 'mittlere Qualifikation', 'Wohnsituation': 'Eigentum', 'Sparkonto': pd.NA, 'Lohnkonto': 'gering', 'Kreditbetrag': 5076, 'Laufzeit': 6, 'Verwendungszweck': 'Unterhaltungselektronik'}]

In [27]:
clf.named_steps['preprocessor'].transform(pd.DataFrame.from_records(data))

array([[   0,    1,    0,    1,    0,    0,    1,    0,    0,    0,    0,
           0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    1,    0,   67, 5076,    6]], dtype=int64)

In [28]:
clf.named_steps['preprocessor'].transform(df_X.loc[:0])

array([[   0,    1,    0,    1,    0,    0,    1,    0,    0,    0,    0,
           0,    0,    1,    1,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    1,    0,   67, 5076,    6]], dtype=int64)

In [29]:
clf.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot'].feature_names_in_ #.named_features['onehot']

array(['Geschlecht', 'Arbeitsstelle', 'Wohnsituation', 'Sparkonto',
       'Lohnkonto', 'Verwendungszweck'], dtype=object)

In [30]:
clf.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot'].categories_

[array(['männlich', 'weiblich'], dtype=object),
 array(['hohe Qualifikation', 'mittlere Qualifikation',
        'niedrige Qualifikation - permanent',
        'niedrige Qualifikation - temporär'], dtype=object),
 array(['Eigentum', 'Miete', 'kostenlos'], dtype=object),
 array(['gering', 'hoch', 'mittel', 'sehr hoch', nan], dtype=object),
 array(['gering', 'hoch', 'mittel', nan], dtype=object),
 array(['Ausbildung', 'Fahrzeug', 'Ferien/andere', 'Geschäft',
        'Haushaltsgeräte', 'Unterhalt', 'Unterhaltungselektronik',
        'Wohnungsreinrichtung'], dtype=object)]

In [31]:
cat_features_cats = [(feat, list(clf.named_steps['preprocessor'].named_transformers_['cat'].named_steps['onehot'].categories_[i])) for i, feat in enumerate(cat_features)]

In [32]:
cat_features_cats

[('Geschlecht', ['männlich', 'weiblich']),
 ('Arbeitsstelle',
  ['hohe Qualifikation',
   'mittlere Qualifikation',
   'niedrige Qualifikation - permanent',
   'niedrige Qualifikation - temporär']),
 ('Wohnsituation', ['Eigentum', 'Miete', 'kostenlos']),
 ('Sparkonto', ['gering', 'hoch', 'mittel', 'sehr hoch', nan]),
 ('Lohnkonto', ['gering', 'hoch', 'mittel', nan]),
 ('Verwendungszweck',
  ['Ausbildung',
   'Fahrzeug',
   'Ferien/andere',
   'Geschäft',
   'Haushaltsgeräte',
   'Unterhalt',
   'Unterhaltungselektronik',
   'Wohnungsreinrichtung'])]

In [33]:
num_features

['Alter', 'Kreditbetrag', 'Laufzeit']

In [34]:
clf.predict(pd.DataFrame.from_records(data))

array([1], dtype=int64)

In [38]:
dump(clf, os.path.join('models', 'clfn.joblib'))

['models\\clfn.joblib']

In [39]:
l = load(os.path.join('models', 'clfn.joblib'))